project 3 requirements
Juank628/vet_database pull request #3
Opened 2023-02-23 22:33 UTC by Juank628

## Vet database: Query multiple tables
In this pull request, I did the following:
- Create a table named owners with the following columns:
  - id: integer (set it as autoincremented PRIMARY KEY)
  - full_name: string
  - age: integer
- Create a table named species with the following columns:
  - id: integer (set it as autoincremented PRIMARY KEY)
  - name: string
- Modify animals table:
  - Make sure that id is set as autoincremented PRIMARY KEY
  - Remove column species
  - Add column species_id which is a foreign key referencing species table
  - Add column owner_id which is a foreign key referencing the owners table
- Insert the following data into the owners table:
  - Sam Smith 34 years old.
  - Jennifer Orwell 19 years old.
  - Bob 45 years old.
  - Melody Pond 77 years old.
  - Dean Winchester 14 years old.
  - Jodie Whittaker 38 years old.
- Insert the following data into the species table:
  - Pokemon
  - Digimon
- Modify your inserted animals so it includes the species_id value:
  - If the name ends in "mon" it will be Digimon
  - All other animals are Pokemon
- Modify your inserted animals to include owner information (owner_id):
  - Sam Smith owns Agumon.
  - Jennifer Orwell owns Gabumon and Pikachu.
  - Bob owns Devimon and Plantmon.
  - Melody Pond owns Charmander, Squirtle, and Blossom.
  - Dean Winchester owns Angemon and Boarmon.
- Write queries (using JOIN) to answer the following questions:
  - What animals belong to Melody Pond?
  - List of all animals that are pokemon (their type is Pokemon).
  - List all owners and their animals, remember to include those that don't own any animal.
  - How many animals are there per species?
  - List all Digimon owned by Jennifer Orwell.
  - List all animals owned by Dean Winchester that haven't tried to escape.
  - Who owns the most animals?
 The following screenshots show the results of the queries:
![image](https://user-images.githubusercontent.com/35902623/221045582-87afb0f5-bc4b-492a-b702-614ab310d99c.png)
![image](https://user-images.githubusercontent.com/35902623/221045697-ba001553-d9e3-4d39-8c06-181ab35aaaa0.png)

2023-02-23 23:13 UTC, Felix45 requested changes
Hi @Juank628 , 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

<img src="https://camo.githubusercontent.com/56bcd754643682fcc078b66eaa7278dead6c9c5013595c875b4ddcbe0f0ef0aa/68747470733a2f2f6d65646961302e67697068792e636f6d2f6d656469612f78554f786668365a4d373565664d3342716f2f67697068792d646f776e73697a65642d6d656469756d2e676966" />

## Highlights :heavy_check_mark: 
- [x] Gitflow is used correctly :white_check_mark: 
- [x] Descriptive pull  request title and summary :white_check_mark: 

## Required Changes ♻️
- [ Required ] I've noticed that the License link on your readme file does not lead to the License in the project root directory, please consider changing the License Link to the one below to fix this. A working License link informs someone who would like to use your code or project how they are Licensed.

```
This project is [MIT](./LICENSE) licensed.
```
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-02-23 23:13 UTC, Felix45 commented on queries.sql
> +SELECT animals.name, species.name, full_name FROM animals JOIN owners ON owners.id = owner_id JOIN species ON species.id = species_id WHERE full_name = 'Jennifer Orwell' AND species.name = 'Digimon';
- [ Required ] I think it would be better if you make this query much more clearer, since you are joining three tables please specify the table where the `species_id` and `owner_id` columns are found. I suggest that you refactor the code as shown below.

```SQL
SELECT animals.*, species.name, full_name 
FROM animals JOIN owners ON owners.id = animals.owner_id 
JOIN species ON species.id = animals.species_id 
WHERE full_name = 'Jennifer Orwell' AND species.name = 'Digimon';
```

2023-02-23 23:13 UTC, Felix45 commented on queries.sql
> +SELECT name, escape_attemps, full_name FROM animals JOIN owners ON owners.id = owner_id WHERE escape_attemps = 0 and full_name = 'Dean Winchester';
- [ Required ] I think it would be better if you make this query much more clearer, since you are joining two tables please specify the table where the `owner_id` column is found. I suggest that you refactor the code as shown below.

```SQL
SELECT name, escape_attemps, full_name 
FROM animals JOIN owners ON owners.id = animals.owner_id 
WHERE escape_attemps = 0 and full_name = 'Dean Winchester';
```

2023-02-23 23:13 UTC, Felix45 commented on queries.sql
> +SELECT COUNT(name), full_name from animals JOIN owners ON owners.id = owner_id GROUP BY full_name ORDER BY COUNT(name) DESC;
- [ Required ] I think it would be better if you make this query much more clearer, since you are joining two tables please specify the table where the `owner_id` column is found. I suggest that you refactor the code as shown below.

```SQL
SELECT COUNT(name), full_name from animals JOIN owners ON owners.id = animals.owner_id 
GROUP BY full_name ORDER BY COUNT(name) DESC;
```

2023-02-24 00:03 UTC, hiromataba approved these changes
# Status: Approved :tada: :tada: :tada: 
Hi @Juank628     :wave: :wave: 

![200w](https://user-images.githubusercontent.com/75126481/151663786-7e0aa330-6769-4ab2-a051-3754be515be9.gif)  

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 



Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-02-24 02:32 UTC, merged